spring:
  datasource:
    # SQLserverデータベース用の設定 ====================================
    url: jdbc:sqlserver://192.168.33.10:1433
    name: testdb
    username: ys
    password: ys
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # ================================================================
   
    # H2データベース用の設定 ===========================================
    # url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # username: sa
    # password: 
    # driver-class-name: org.h2.Driver
    # initialization-mode: embedded
    # schema: classpath:schema.sql
    # data: classpath:data.sql
    # ================================================================

    # 共通設定
    sql-script-encoding: UTF-8

  profiles:
    active: dev
  h2:
    console:
      enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    
server:
  port: 8081
